MeeTeamIdle/MeeTeam_BackEnd

.github/workflows/deploy.yml
.gitignore
docker/Dockerfile
docker/docker-compose.blue.yml
docker/docker-compose.green.yml

- #4 
> 간단하게 구현한 내용과 방법에 대한 설명
> 
- applicaton-dev.yml secret 추가
- github action에서 파일 복사 job 추가
- Dockerfile에서 profile 명령 추가
> 나중에 다시 고민해야할 내용이 있는 내용
> 
> 없을 경우 작성 X
> 있을 경우 작성 후 이슈 남기고 해당 PR 링크
> 
close #4

[ADD] Applicaton.yml 파일로 profile 설정 추가

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/entity/RecruitmentRole.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role_skill/entity/RecruitmentRoleSkill.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role_skill/repository/RecruitmentRoleSkillRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role_skill/service/RecruitmentRoleSkillService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_tag/repository/RecruitmentTagRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_tag/service/RecruitmentTagService.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_role_skill/RecruitmentRoleSkillRepositoryTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_role_skill/RecruitmentRoleSkillServiceTest.java

- feat/
- closed #111 
- 구인글 수정을 구현했습니다.
- 일부 자잘한 테스트는 생략했습니다.
```
{
"scope": "교내",
"category": "프로젝트",
"deadline": "2023-02-05",
"proceedingStart": "2023-02-01",
"proceedingEnd": "2023-05-01",
"fieldId": 1,
"proceedType": "온라인",
"courseTag": {
"isCourse": true,
"courseTagName": "응용소프트웨어실습",
"courseProfessor": "김용혁"
},
"tags": ["newSpring","newJava","newJPA"],
"recruitmentRoles": [
{
"roleId": 1,
"count": 3,
"skillIds": [4, 5, 6]
}
],
"title": "졸작 사람 구합니다22",
"content": "안녕하세요. 사람구하는데 진짜 고수만 구해요.."
}
```
- 하나의 트랜잭션으로 묶기 위해서 파사드 패턴을 사용했습니다!
- 특이점으로, `recruitmentRole` 과 `recruitmentRoleSkill` 에 대한 수정을 `recruitmentRoleService`에서 진행했습니다!
- 이 부분에 대해서 고민이 좀 많았는데요. 두 객체가 너무 연관이 깊게 되어 있어서 여러 방법에 대해 고민했었습니다.
1. 각각의 서비스 레이어에서 각각의 엔티티를 삭제 후 새로운 엔티티를 생성
- `구인역할 수정`(구인역할 삭제 및 생성) -> `구인역할스킬 수정`(구인역할스킬 …

[FEAT] 구인글 수정 API

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/SetOpenKakaoLinkRequestDto.java

- feat/#135
- closed #135
오픈카톡방 링크 설정 API 스웨거 추가

[DOCS] 오픈카톡방 링크 설정 API 스웨거 추가

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/PaginationSearchPostResponseDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/SearchRecruitmentPostsResponseDto.java
src/main/java/synk/meeteam/global/dto/PageInfo.java
src/main/java/synk/meeteam/security/config/SecurityConfig.java

- feat/#142
- closed #142
구인글 목록 검색 조회 API 스웨거 작성하였습니다.
| id | category |
|:--|:----:|
| 1 | 프로젝트 |
| 2 | 스터디  |
| 3 | 공모전  |  
| id | scope |
|:--|:----:|
| 1 | 교외 |
| 2 | 교내  |  
분야의 경우에는 현재 db에 저장하며 id는 1(개발)로 고정입니다!
분야 조회 API를 간단히 추가하는 것도 좋을 것 같네요!

[DOCS] 구인글 목록 검색 조회 API 스웨거 작성

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/CreateCommentRequestDto.java
src/main/java/synk/meeteam/global/config/SwaggerConfig.java

- feat/
- closed #139 
- 댓글 등록 API 스웨거 추가했습니다.
- 구인쪽 API가 점점 많아지는 것 같아서 댓글 부분만 따로 분리해봤는데 의견 궁금합니다!
- 더 나눌려다가 오히려 더 나누면 복잡해질 거 같아서 일단 댓글 부분만 뺴봤습니다.
- 보시는데 불편하지 않으셨다면, 이렇게 분리하지 않고 기존 방식대로 진행하겠습니다!

[DOCS] 댓글 등록 API 스웨거 추가

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/DeleteCommentRequestDto.java

- feat/
- closed #157 
- 메서드를 delete로 하려다가, 저희가 실제 db에 아예 완전 삭제시키는게 아니라 boolean 값만 바꾸고, 데이터를 남겨두고는 있어서 patch로 해봤습니다..! 의견 궁금합니다!
- 요청 url : PATCH {{domain}}/recruitment/postings/1/comment
- 요청 바디 : 
```
{
"groupNumber": 2,
"groupOrder": 3
}
```

[DOCS] 댓글 삭제 API 스웨거 추가

---

src/main/java/synk/meeteam/domain/common/course/entity/Professor.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/entity/RecruitmentComment.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/exception/RecruitmentCommentExceptionType.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/repository/RecruitmentCommentRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/repository/RecruitmentCommentRepositoryCustomImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/vo/RecruitmentCommentVO.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/DeleteCommentRequestDto.java
src/main/java/synk/meeteam/global/util/Encryption.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentEntityTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java

- feat/
- closed #159 
-댓글 삭제 API 구현했습니다.
- 조회 로직도 같이 수정했습니다!

[FEAT] 댓글 삭제 API

---

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/GetProfilePortfolioDto.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/response/GetUserPortfolioResponseDto.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/PortfolioMapper.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepository.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioService.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
src/main/java/synk/meeteam/domain/user/user/api/UserApi.java
src/main/java/synk/meeteam/domain/user/user/api/UserController.java
src/main/java/synk/meeteam/domain/user/user/service/ProfileFacade.java
src/main/java/synk/meeteam/global/dto/SliceInfo.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioFixture.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java
src/test/java/synk/meeteam/domain/user/user/UserControllerTest.java
src/test/java/synk/meeteam/domain/user/user/UserFixture.java

- feat/#166 -> dev
- closed #166 
내 포트폴리오 목록 조회 API 구현했습니다.
일부 조회 로직 수정하였습니다.
- TODO 이미지 url
- 현재 이미지 이름만 return 하고 있습니다. 추후 이미지 업로드 구현되면 추가하려고 합니다. 
- 기능적 분류를 위하여 `Repository`와 `Service`는 `Portfolio`를 `Controller`는 `User`를 이용하였습니다.
- Repository에서 Dto로 조회 후, `Service`에서 Dto 변환(추후 이미지 url 변환 과정 추가예정), `Controller`는 단순 return 합니다.
- `Pageable` 객체를 줄 때, `PageRequest.of` 메소드를 이용하는데 이때 page는 인덱스 개념이어서 1을 빼주는 과정을 `Service`에서 진행합니다.
- `SliceInfo` 레코드 정의하였습니다.

[FEAT] 내 포트폴리오 목록 조회 API

---

build.gradle
src/main/java/synk/meeteam/domain/common/role/dto/RoleDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantInfoResponseDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetRoleDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/entity/RecruitmentComment.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/ModifyCommentRequestDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentEntityTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java

- feat/
- closed #176 
- 댓글 수정 API 구현했습니다.
- PATCH 메서드 지원을 위해 의존성 추가했습니다!
- 관련 자료 : https://learnote-dev.com/java/Spring-TestRestTemplate-Patch-%EC%9A%94%EC%B2%AD-%EC%98%A4%EB%A5%98%EB%82%A0-%EB%95%8C/

[FEAT] 댓글 수정 API

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/request/ProcessApplicantRequestDto.java

- feat/
- closed #186 
- 신청자 거절 API 스웨거
- 누구 담당인지 몰라 두 분다 리뷰어로 뒀습니다~

[DOCS] 신청자 거절 API 스웨거 추가

---

build.gradle
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitStatus.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitmentApplicant.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantExceptionType.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/facade/RecruitmentApplicantFacade.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/RecruitmentPostMapper.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/entity/RecruitmentRole.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
src/main/java/synk/meeteam/infra/mail/MailService.java
src/main/java/synk/meeteam/infra/mail/MailText.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantEntityTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantFixture.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleEntityTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleRepositoryTest.java

- feat/
- closed #182 
- 신청자 승인 API 를 구현했습니다.
* 이 부분에 대해서 고민이 많았습니다..!
* 신청자가 1명일 경우에는 로직이 매우 간단하지만, 여러명이 `List` 로 올 수 있는 부분을 생각하다 보니까 복잡해졌는데요!
* 결국 업데이트 쿼리가 굉장히 많이 발생한다는 문제가 있었습니다.
* N명을 승인한다고 가정하고 쿼리 횟수를 비교해보겠습니다.
1. 단순한 방법(더티 체킹 기술을 활용) : `N`(신청자 수 만큼 업데이트 쿼리) + `1`(구인글 응답 횟수 업데이트 쿼리) + `구인역할수만큼`(구인역할 테이블의 구인된 인원을 증가시키기 위해)
2. 벌크 연산 : `1`(신청자 수와 관련없이 1번 업데이트 쿼리) +  `1`(구인글 응답 횟수 업데이트 쿼리) + `구인역할수만큼`(구인역할 테이블의 구인된 인원을 증가시키기 위해)
* 결국 1번과 2번의 차이는 신청자 테이블에서 신청 승인으로 업데이트 쿼리 수를 `N` -> `1` 으로 줄였습니다!
* `구인역할수만큼`의 쿼리 횟수도 `1`번으로 줄이고 싶었는데요!
* 고민하다보니 물리적으로 불가능하지 않나? 라는 생각이 들었습니다.
* 왜냐하면, 구인역할마다 승인된 인원이 다르기 때문에 1번의 쿼리로는 불가능하다고 생각했습니다! (제가 이 부분을 좀 간단하게 설명했는데 혹시 구체적으로 설명필요하시면 말씀주세요!)
* 하지만 부겸님께서 생각하실 때, 좋은 방법이 있어서 `구인역할수만큼`의 쿼리 횟수를 `1`번의 쿼리로 처리할 수 있는 방법이 있다면 정말 환영입니다 ㅎㅎ
* 하지만 이렇게 하다보니, 더티체킹으로는 벌크연산이 …

[FEAT] 신청자 승인 API

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantResponseDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostSearchRepositoryTest.java

- feat/
- closed #204
- 신청자 목록 조회에 이메일 추가
- 신청자 목록 무한스크롤로 수정
```
{
"applicants": [
{
"applicantId": 1,
"userId": "4OaVE421DSwR63xfKf6vxA",
"nickname": "송민규짱짱맨",
"profileImg": "https://meeteam-backend-bucket.s3.ap-northeast-2.amazonaws.com/user/40aVE421DSwR63xfKf6vxA%3D%3D.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240408T155832Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAWUWPATOABI5ONYWN%2F20240408%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Signature=21eba567ea1f2cab48e2c229ebc27e850992fc27eaae5b6d0299f3ca2aa506ac",
"name": "송민규",
"score": 3.9,
"universityName": "광운대학교",
"departmentName": "소프트웨어학부",
"email": "thdalsrb79@naver.com",
"year": 2018,
"applyRoleName": "소프트웨어 엔지니어",
"message": "나 잘할 수 있음"
},
{
"applicantId": 2,
"userId": "b_VkcONhMCJIbGlD6yoTkw", …
```

[FIX] 신청자 목록 조회 수정

---

src/main/java/synk/meeteam/domain/user/user/dto/UpdateProfileCommandMapper.java
src/main/java/synk/meeteam/domain/user/user/dto/request/UpdateProfileRequestDto.java

- feat/#211
- closed #211
- 프로필 수정 API에 누락된 닉네임 공개여부필드 추가했습니다.

[FIX] 프로필 수정 API 닉네임 공개여부 필드 추가

---

src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java

- feat/#224 -> dev
- closed #224
- 내 포트폴리오 조회시에 정렬조건으로 id순을 추가하였습니다.
- 내 핀 포트폴리오 조회시, 정렬기준을 생성일 -> pinOrder 순으로 변경하였습니다.
- 내 핀 포트폴리오 id로 설정하기 위한 조회 시에, 빈 id 리스트에 대한 예외처리 하였습니다.
- 테스트코드 일부 함수명 변경하였습니다.

[FIX] 내 포트폴리오 조회 관련 버그 해결

---

build.gradle
src/main/java/synk/meeteam/infra/rds/SshDataSourceConfig.java
src/main/java/synk/meeteam/infra/rds/SshTunnelingInitializer.java
src/main/resources/logback-spring.xml

- feat/
- closed #234
- 로컬 spring에서 rds 연결 가능하도록 구현했습니다!
- profile 중에 `stg` 를 사용했습니다!
- 스테이징 프로파일 (staging): 프로덕션 환경으로 전환하기 전에 사용되는 테스트 환경입니다. 실제 운영 환경과 유사한 설정이 포함될 수 있습니다.
- 실행시키기 위해선 application-stg.yml 가 필요합니다!

[FEAT] 로컬 spring에서 rds 연결 가능하도록 구현

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantInfoResponseDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
src/main/java/synk/meeteam/domain/user/user/entity/User.java
src/main/java/synk/meeteam/domain/user/user/service/UserService.java
src/main/java/synk/meeteam/domain/user/user/service/UserServiceImpl.java

- feat/
- closed #242 
- 최초 접근 처리에 대한 API 를 구현했습니다.
- User 엔티티의 디폴트값을 true로 해야했는데 false로 해서.. 수정했습니다..!
- 매퍼 관련된 오류까지 같이 커밋했습니다....ㅎㅎ....

[FEAT] 최초 접근 기능 구현

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementApi.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/SimpleRecruitmentPostMapper.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/SimpleRecruitmentPostDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentManagementRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentManagementRepositoryImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/expression/ExpressionUtils.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/vo/RecruitmentPostVo.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostFixture.java

- feat/#245 -> dev
- closed #245
- 구인글 관리 - 북마크한 구인글
- 구인글 관리 - 신청한 구인글
- 구인글 관리 - 내가 작성한 구인글
- 기존 구인글 검색
- 필드 추가 : `writerId`, `isClosed` 
- 구인글 작성자의 이미지를 도메인의 이미지로 할 것인지 궁금합니다.
- 만약 그렇다면, 이미지 이름을 클라이언트에서 userId를 받아야 할 것 같습니다.
- 코드가 깔끔하지 못합니다. 혹시 좋은 아이디어 있으면 추천해주시면 감사하겠습니다.

[FEAT] 구인글 관리 API 구현

---

src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioController.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepository.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioService.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
src/main/java/synk/meeteam/domain/user/user/api/UserController.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java
src/test/java/synk/meeteam/domain/user/user/UserControllerTest.java

- feat/#256 -> dev
- closed #256
- 포트폴리오 목록 페이지네이션으로 조회하는 API 추가하였습니다.
- 기존의 프로필 페이지에서 제공하던 포트폴리오 목록 조회 API에 이미지 url변환 로직을 추가하였습니다.
- 일부 메소드 명 변경하였습니다.

[FEAT] 내 포트폴리오 페이지네이션 조회 구현

---

src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioApi.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioController.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioService.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioFixture.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java

- feat/#253 -> dev
- closed #253
- 포트폴리오 삭제 API 구현하였습니다.
- 핀 포트폴리오 조회 로직에 자신의 포트폴리오만 조회하는 로직이 빠져있어 추가하였습니다.
- 기존 테스트 코드 문제있는 부분을 해결하였습니다.
- 알려주신 자료를 참고하여 sequence가 변하지 않도록 `test-portfolio.sql` 을 추가하여 테스트 코드 문제를 해결하였습니다.

[FEAT] 포트폴리오 삭제 API 구현

---

docker/Dockerfile

- feat/#274 -> dev
- closed #274
- 현재 codeDeploy에서 ScriptTimeOut 이 발생합니다. 원인으로 해당 스크립트에서 이미지를 가져오기 전에 timezone을 설정하는 것이 문제가 되었다고 판단하여 다음과 같이 수정하였습니다.

[FIX] DockerFile 타임존 설정 코드 순서 수정

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java

- feat/#272 -> dev
- closed #272
- 기존 구인글 게시판에서 조회되는 검색 API에 마감된 구인글이 제공되는 부분을 제공하지 않도록 변경하였습니다.

[FIX] 구인글 마감인 경우 제외하도록 수정

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/facade/RecruitmentApplicantFacade.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
src/main/java/synk/meeteam/global/config/AsyncConfig.java
src/main/java/synk/meeteam/infra/mail/MailService.java

- feat/#197 -> dev
- closed #197
- 메일 전송 부분을 비동기로 처리하게 했습니다!
- 그래도 나름 1.7s -> 0.6s 정도로 줄어들었습니다!
-

[REFACTOR] 메일 비동기 전송 구현

---

src/main/java/synk/meeteam/domain/auth/api/AuthController.java
src/main/java/synk/meeteam/domain/auth/exception/AuthExceptionType.java
src/main/java/synk/meeteam/domain/auth/service/AuthService.java
src/main/java/synk/meeteam/infra/mail/MailService.java

- feat/#303 -> dev
- closed #303

[CHORE] 이메일 인증 후 중복회원 가입 방지 추가

---

src/main/java/synk/meeteam/domain/auth/exception/AuthExceptionType.java
src/main/java/synk/meeteam/domain/auth/service/AuthService.java
src/main/java/synk/meeteam/domain/common/department/entity/Department.java
src/main/java/synk/meeteam/domain/common/university/entity/University.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/CourseTagDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/CreateRecruitmentPostRequestDto.java
src/main/java/synk/meeteam/domain/user/user/repository/UserRepository.java
src/main/java/synk/meeteam/global/aop/ExecutionLoggingAop.java

- feat/#308 -> dev
- closed #308
- 구인역할 최대갯수 10개로 조정 및 글자수 제한
- 로깅 인터셉터 출력 방식 변경
- 가입 단계에서 이미 존재하는 이메일인지 검증
- 대학, 학과 엔티티 길이 제한 변경

[CHORE] QA 내용 반영

---

src/main/java/synk/meeteam/global/util/HtmlCharacterEscapes.java

- feat/#315 -> dev
- closed #315 
- 필터를 변경했습니다.

[FIX] xss 필터 수정

---

.github/workflows/deploy.yml
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
src/main/java/synk/meeteam/domain/user/user/entity/User.java
src/main/java/synk/meeteam/infra/mail/MailService.java
src/main/java/synk/meeteam/infra/mail/MailText.java

- feat/#307 -> dev
- closed #307 
- 구인 신청 시 메일 발송 구현했습니다.
- 깃헙 시크릿값에 메일 폼 넣었습니다.
* 이름 같은 이유는 로컬에서 했기에 그렇습니다!

[FEAT] 구인 신청시 메일 발송 구현

---

src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/exception/PortfolioExceptionType.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioFacade.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java

- hotfix/#330 -> dev
- closed #330
- 기존에 포트폴리오 삭제 이후에도 조회되는 부분을 수정하였습니다.
- 핀 포트폴리오의 경우 삭제 이후 핀 순서를 재정렬해주는 예외처리를 추가하였습니다.
위 처럼 핀 설정 여부와 관계없이 삭제 가능하며, 아래와 같이 조회 시 제공되지 않습니다.

[FIX] 포트폴리오 삭제로직 수정

---

src/main/java/synk/meeteam/infra/redis/repository/RedisTokenRepository.java
src/main/java/synk/meeteam/security/jwt/service/JwtService.java

- feat/#335 -> dev
- closed #335 
- 로그아웃 및 토큰 재발행 로직에서 플랫폼 id -> userId로 변경했습니다.

[CHORE] 로그아웃 및 토큰 재발행 로직 수정

---

src/main/java/synk/meeteam/global/util/UnescapedFieldSerializer.java

- feat/#342 -> dev
- closed #342 
- 프론트에서 받을 때, Object가 아닌 String으로 받게 되는 문제가 발생했습니다.
- 정확한 원인인지는 모르겠지만 시점을 생각해봤을 때, RawValue로 저장하도록 코드 변경 후 부터 에러가 발생했다고 생각했습니다.
- 그래서 "content" 변수도 String으로 저장하되, String으로 저장하기 전에 이스케이핑 설정을 초기화 시켜두고, 저장 후에 다시 적용하는 방식으로 구현했습니다.
- 프론트에서 테스트를 해봐야 할 것 같습니다..! 로컬에서는 정확하게 에러탐지가 어렵네요..

[FIX] content에 한해 이스케이핑 적용 해제

---

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java

- hotfix/#345 -> dev
- closed #345
- 구인글 검색 시에 total count가 잘못나오는 오류가 있어 수정했습니다.

[FIX] 구인글 검색 API total count 버그 수정

---

src/main/java/synk/meeteam/domain/user/user/api/UserApi.java
src/main/java/synk/meeteam/domain/user/user/api/UserController.java
src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfileImageResponseDto.java
src/main/java/synk/meeteam/domain/user/user/service/UserServiceImpl.java

- feat/#337 -> dev
- closed #337 
- 내 프로필 이미지 조회 기능 구현했습니다.

[FEAT] 내 프로필 이미지 조회 기능 구현

---

src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java
src/main/java/synk/meeteam/domain/portfolio/portfolio_link/repository/PortfolioLinkRepository.java
src/main/java/synk/meeteam/domain/portfolio/portfolio_skill/repository/PortfolioSkillRepository.java
src/main/java/synk/meeteam/domain/recruitment/bookmark/repository/BookmarkRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/repository/RecruitmentCommentRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_role_skill/repository/RecruitmentRoleSkillRepository.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_tag/repository/RecruitmentTagRepository.java
src/main/java/synk/meeteam/domain/user/award/repository/AwardRepository.java
src/main/java/synk/meeteam/domain/user/user/api/UserApi.java
src/main/java/synk/meeteam/domain/user/user/api/UserController.java
src/main/java/synk/meeteam/domain/user/user/service/UserManagementService.java
src/main/java/synk/meeteam/domain/user/user_link/repository/UserLinkRepository.java
src/main/java/synk/meeteam/domain/user/user_skill/repository/UserSkillRepository.java

- 회원 탈퇴 구현했습니다.
- 처음에는 CASCADE 옵션을 사용해서 구현하려고 했습니다.
- 하지만 다음과 같은 생각이 들었는데요!
1. `CASCADE`의 위험성 : 개인적으로 `CASCADE` 옵션이 매우 위험한 옵션이라고 생각했습니다! 물론 저희가 잘 신경쓰면 괜찮을 수 있습니다. 하지만 그럼에도 불구하고, 개발자가 의도하지 않은 데이터가 사라질 수 있다는 가능성이 있다는 점이 개인적으로 좋지 않다고 생각했습니다. 만약 휴먼 에러로 잘못된 설정을 한다면, 잘못하면 가장 중요한 DB가 다 날라갈 수도 있겠다라는 생각이 들었습니다! 개인적으로 저는 db에 hard delete를 할 경우, 사라지는 모든 데이터를 개발자가 명시적으로 의도했음 좋겠다고 생각합니다!
2. `CASCADE`의 범위 설정 : 그럼에도 불구하고, `CASCADE` 를 사용할 경우 구인글에 적용했다고 가정해보겠습니다. 그렇게 되면 구인 관련된 것은 사라지겠지만, 외부키로 설정된 Tag나 role 부분도 삭제될 수 있겠다고 생각이 들었습니다. 이 부분은 정확하지 않거나 제가 방법을 모르는 것 일 수도 있습니다! 아무튼 그런 이유 때문에도 사용이 꺼려졌습니다!
3. 성능 이슈 : 이렇게 되면 가장 큰 trade-off 가 DB I/O가 증가한다는 것입니다. 사실 CASCADE 연산과 여러번 delete 연산의 차이가 어느정도 일지는 아직 검증이 안되어 있습니다. 그럼에도 불구하고, 여러번 delete 연산이 훨씬 더 느릴 가능성은 있다고 생각이 들었습니다. 하지만 저는 개인적으로 모든 API의 성능을 고려하는 것도 비용이라고 …

[FEAT] 회원 탈퇴 구현

---

src/main/java/synk/meeteam/domain/recruitment/bookmark/repository/BookmarkRepository.java
src/main/java/synk/meeteam/domain/user/user/service/UserManagementService.java

- feat/#356 -> dev
- closed #356 
- 삭제하려는 유저가 했던 북마크 뿐만 아니라, 삭제하려는 구인글에 대한 북마크도 삭제해야해서 해당 부분 수정했습니다.

[FIX] 삭제하려는 구인글 북마크 이력 삭제 추가

---

.github/workflows/deploy.yml
docker/Dockerfile
src/main/java/synk/meeteam/infra/aws/service/CloudFrontService.java

- hotfix/#368 -> dev
- closed #368
- DockerFile 을 수정하여, private_key가 container 내부에 복제되도록 변경하였습니다.

[FIX] Cloudfront PrivateKey 이슈 해결 

---

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/SimplePortfolioDto.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioFacade.java
src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantDto.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/repository/RecruitmentCommentRepositoryCustomImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/vo/RecruitmentCommentVO.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentManagementRepositoryImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/vo/RecruitmentPostVo.java
src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
src/main/java/synk/meeteam/domain/user/user/api/UserController.java
src/main/java/synk/meeteam/domain/user/user/entity/User.java
src/main/java/synk/meeteam/domain/user/user/service/ProfileFacade.java
src/main/java/synk/meeteam/global/api/ServerProfileController.java
src/main/java/synk/meeteam/infra/aws/service/CloudFrontService.java
src/main/java/synk/meeteam/infra/aws/strategy/NoPortfolioStrategy.java
src/main/java/synk/meeteam/infra/aws/strategy/PortfolioExistStrategy.java
src/main/java/synk/meeteam/infra/aws/strategy/PortfolioStrategy.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioFixture.java
src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentServiceTest.java
src/test/java/synk/meeteam/domain/user/user/UserFixture.java

- fix/#390 -> dev
- closed #390
- 문자열 쿼리 기반으로 파일의 버전을 관리하도록 변경하였습니다.
- 이에 따라 일부 스키마 변경이 이루어졌습니다.
- `user`에  `imgVersion` 추가
- `portfolio`에 `version` 추가
- 일부 로직에서 dto에 version 관련 데이터가 추가되었습니다.
- 현재 진행한 방식의 경우, 기능 구현을 위한 코드로 되어있습니다.
- 이미지에 대한 버전을 dto로 조회해와서 그대로 서빙하기 때문에 이상하다고 느껴지긴합니다.
- 때문에 내부에서 version을 제외한 dto로 한번 더 변환하면 어떨까 싶은데 어떻게 생각하시나요?

[FIX] 이미지 캐싱 오류 해결 및 일부 코드 개선
