MeeTeamIdle/MeeTeam_BackEnd

src/main/java/synk/meeteam/domain/auth/api/AuthController.java, src/main/java/synk/meeteam/domain/auth/dto/request/SignUpUserRequestDto.java, src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseDto.java, src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseMapper.java, src/main/java/synk/meeteam/domain/auth/service/vo/AuthUserVo.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/RecruitmentPostMapper.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/CreateRecruitmentPostRequestDto.java, src/main/java/synk/meeteam/security/jwt/service/JwtService.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
- feat/
- closed #102
- 변수명들 변경
=> [CHORE] 변수명 및 변수타입 변경

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/CreateRecruitmentPostRequestDto.java
- feat/
- closed #104 
- 클라이언트 요청에 따라 변수명 변경했습니다.
=> [FIX] Tags -> tags 변경

src/main/java/synk/meeteam/security/config/SecurityConfig.java
=> [FIX] 화이트 리스트 변경

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/GetProfilePortfolioDto.java, src/main/java/synk/meeteam/domain/user/user/api/UserApi.java, src/main/java/synk/meeteam/domain/user/user/api/UserController.java, src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfileAwardDto.java, src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfileEmailDto.java, src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfileLinkDto.java, src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfilePhoneDto.java, src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfileResponseDto.java, src/main/java/synk/meeteam/security/config/SecurityConfig.java
- feat/#94 ->dev
- closed #94
프로필 조회 API 스웨거 입니다.
```json
{
"imageUrl": "https://image.png",
"userName": "민지",
"nickname": "minji",
"isUserNamePublic": false,
"interest": "백엔드 개발자",
"introduction": "한줄소개입니다.",
"aboutMe": "한줄소개보다 구체적인 자기소개입니다.",
"universityEmail": {
"content": "skqnrua5123@kw.ac.kr",
"isPublic": true,
"isDefault": true
},
"subEmail": {
"content": "skqnrua5123@kw.ac.kr",
"isPublic": true,
"isDefault": true
},
"phone": {
"content": "010-1234-5678",
"isPublic": true
},
"university": "광운대학교",
"department": "소프트웨어학부",
"maxGpa": 4.5,
"gpa": 4.3,
"year": 2019,
"portfolios": [
{
"id": 1,
"title": "Meeteam",
"mainImageUrl": "https://~~",
"startDate": "2024-03-25",
"endDate": "2024-03-25",
"field": "개발",
"role": "백엔드 개발자",
"skills": [
{
"id": 1,
"name": "파이썬"
}
]
}
],
"links": [
{ …
```
=> [DOCS] 프로필 조회 API 스웨거

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
- feat/
- closed #106
* 요청 :  PUT {domain}/postings/{id}
* 구인글 생성과 같은 요청 body를 사용했습니다!
=> [DOCS] 구인글 수정 API 스웨거 추가

src/main/java/synk/meeteam/global/entity/ProceedType.java
- feat/
- closed #113
- 변수명도 NO_MATTER로 변경했는데 의견 궁금합니다!
=> [FIX] 온/오프라인 -> 상관없음으로 수정

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
- feat/
- closed #117 
- url : POST {domain}/recruitment/postings/{id}/bookmark
=> [DOCS] 구인글 북마크 API 스웨거 추가

build.gradle
- feat/
- closed #121
- Jacoco 세팅 했습니다!
- https://techblog.woowahan.com/2661/
=> [ADD] Jacoco 세팅

.github/workflows/build.yml, .github/workflows/deploy.yml
- feat/#91
- closed #91
스크립트 이름 변경했습니다.
=> [INFRA] CI/CD 수정

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
- feat/
- closed #130 
- 북마크 API와 url은 동일하지만, delete 메서드를 사용해봤습니다!
- 이것에 대해 의견 궁금합니다 :)
=> [DOCS] 구인글 북마크 취소 API 스웨거 추가

src/main/java/synk/meeteam/domain/recruitment/bookmark/exception/BookmarkExceptionType.java, src/main/java/synk/meeteam/domain/recruitment/bookmark/repository/BookmarkRepository.java, src/main/java/synk/meeteam/domain/recruitment/bookmark/service/BookmarkService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/exception/RecruitmentPostExceptionType.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/test/java/synk/meeteam/domain/recruitment/bookmark/BookmarkServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostFixture.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java, src/test/java/synk/meeteam/global/enums/EnumsTest.java
- feat/
- closed #132 
- 구인글 취소 구현했습니다.
- 구인글 조회하는 로직을 파사드 패턴 내에서 변경하는 것으로 수정했습니다!
- 엔티티 객체에 북마크 수가 0이하일 경우 예외발생하도록 구현했는데 의견 궁금합니다!
=> [FEAT] 북마크 취소 API

src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioFixture.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java
- feat/#136
- closed #136
테스트 코드 정상동작하도록 수정하였습니다.
=> [FIX] PortfolioFixture 빌더 mainImageFileName 필드값 추가

src/main/java/synk/meeteam/domain/recruitment/bookmark/service/BookmarkService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetCommentResponseDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetReplyResponseDto.java, src/main/java/synk/meeteam/infra/s3/S3FileName.java
- feat/
- closed #143 
- closed #95 
- 반환 데이터 수정 했습니다!
```
{
"isWriter": true,
"writerId": "4OaVE421DSwR63xfKf6vxA==",
"isClosed": false,
"isBookmarked": false,
"category": "프로젝트",
"title": "이건제목입니다!!",
"createdAt": "2023-02-01T00:00",
"bookmarkCount": 5,
"writerNickname": "송민규짱짱맨",
"writerProfileImg": "https://meeteam-backend-bucket.s3.ap-northeast-2.amazonaws.com/user/40aVE421DSwR63xfKf6vxA%3D%3D.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240328T041504Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAWUWPATOABI5ONYWN%2F20240328%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Signature=74c69a962cd697c5126b2fae2ca36f70ed1307f3d9b1214732737f0d4022fa94",
"responseRate": 0.0,
"writerScore": 3.9,
"proceedingStart": "2024-04-21",
"proceedingEnd": "2024-03-21",
"proceedType": …
```
=> [FIX] 특정 구인글 조회 API 반환 데이터 수정

src/main/java/synk/meeteam/domain/user/user/repository/UserCustomRepositoryImpl.java
- feat/#149
- closed #149
함수를 잘못 짠 부분이 존재했네요.. 추후 테스트 코드 추가하겠습니다.
=> [FIX] UserRepository 함수 수정

src/main/java/synk/meeteam/domain/user/user/dto/UpdateProfileCommandMapper.java, src/main/java/synk/meeteam/domain/user/user/dto/command/UpdateInfoCommand.java, src/main/java/synk/meeteam/domain/user/user/dto/request/UpdateProfileRequestDto.java, src/main/java/synk/meeteam/domain/user/user/service/UserServiceImpl.java
- feat/#134
- closed #134
프론트 요청에 따라 다음과 같이 변경하였습니다.
- `phoneNumber `-> `phone`
- `name `-> `userName`
- `isPublicPhone `-> `isPhonePublic`
- `isPublicSubEmail `-> `isSubEmailPublic`
- `isPublicUniversityEmail `-> `isUniversityEmailPublic`
- `interest_id`-> `interestId`
- `isSchoolMain `-> `isUniversityMain`
```json
{
"userName": "부겸",
"nickname": "goder",
"imageFileName": "string",
"phone": "010-1234-5678",
"isPhonePublic": true,
"isUniversityMain": true,
"subEmail": "goder0@naver.com",
"isSubEmailPublic": true,
"isUniversityEmailPublic": true,
"introduction": "고통을 즐기는 개발자",
"aboutMe": "안녕하세요. 저는 프로그래밍 자체를 좋아하지만, 아직은 부족한 백엔드 개발자 지망생입니다. 협업의 중요하게 생각하며 다양한 방식의 커뮤니케이션을 하기 위해 노력하고 있으며, 더 나은 코드를 만들기 위한 지식을 쌓는 중에 있습니다.",
"interestId": 1,
"gpa": 4,
"maxGpa": 4.5,
"skills": [
1,
2,
3
],
"links": …
```
=> [FIX] 프로필 수정 API 요청 Dto 변수명 수정

src/main/java/synk/meeteam/security/config/SecurityConfig.java
- feat/
- closed #151 
- delete 추가
=> [FIX] CORS delete 추가

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/request/SetLinkRequestDto.java
- feat/
- closed #161 
- 기존과 다른 url 설정을 했습니다!
- 만약 어푸르브 되면, 기존의 것은 삭제하겠습니다!
=> [DOCS] 오픈카톡방 링크 설정 API 스웨거 PR

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantException.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantExceptionType.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
- feat/
- closed #165 
- 링크 설정 API 구현했습니다.
- `test-recruitment-applicant.sql` 파일이 추가됐습니다.
=> [FEAT] 링크 설정 API

src/main/java/synk/meeteam/domain/common/role/dto/RoleDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantInfoResponseDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantResponseDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantsResponseDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetRecruitmentRoleStatusResponseDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
- feat/
- closed #170 
```
{
"title": "이건제목입니다!!",
"link": "www.kakaolink",
"recruitmentRoleStatus": [
{
"roleName": "소프트웨어 엔지니어",
"recruitMemberCount": 3,
"approvedMemberCount": 0
},
{
"roleName": "웹 개발자",
"recruitMemberCount": 2,
"approvedMemberCount": 0
}
],
"roles": [
{
"id": 1,
"name": "소프트웨어 엔지니어"
},
{
"id": 2,
"name": "웹 개발자"
}
]
}
```
- `신청 정보 조회 API` 와 `신청자 목록 조회 API`를 분리하기로 했습니다.
- 해당 API는 `신청 정보 조회 API` 입니다!
=> [FEAT] 신청 관리 정보 조회 API 

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/request/ApproveApplicantRequestDto.java
- feat/
- closed #178 
- 요청 URL  예시 :` {{domain}}/recruitment/applicant/1/approve?applicant-id=3`
- `applicant-id`는 신청자 목록 조회 API에서 제가 드릴 예정입니다!
=> [DOCS] 신청자 승인 API 스웨거 추가

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantResponseDto.java
- feat/
- closed #188 
- 요청 url 예시 : GET /recruitment/applicant/1/applicants?role=2
- 요청 url이 좀 아쉬운거 같기도 한데요.. 혹시 좋은 제안 있으면 환영입니다 !!
=> [DOCS] 신청자 목록 조회 API 스웨거 추가

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
- feat/
- closed #195 
- DELETE {domain}/recruitment/postings/1/apply
- url 관해서 더 좋은 의견 있으시면 환영입니다~~!
=> [DOCS] 구인 신청 취소 API 스웨거 추가

.github/workflows/deploy.yml
- feat/
- closed #198 
- html 템플릿 파일을 cd 동작할 때, 생성하도록 만들었습니다!
=> [FIX] html 코드 주입 작업 추가

.github/workflows/deploy.yml
=> [FIX] html 생성 작업 수정

src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/exception/PortfolioExceptionType.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepository.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioService.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java, src/main/java/synk/meeteam/domain/user/award/repository/AwardRepository.java, src/main/java/synk/meeteam/domain/user/award/service/AwardService.java, src/main/java/synk/meeteam/domain/user/award/service/AwardServiceImpl.java, src/main/java/synk/meeteam/domain/user/user/dto/UpdateProfileCommandMapper.java, src/main/java/synk/meeteam/domain/user/user/dto/command/UpdateInfoCommand.java, src/main/java/synk/meeteam/domain/user/user/dto/request/UpdateProfileRequestDto.java, src/main/java/synk/meeteam/domain/user/user/entity/User.java, src/main/java/synk/meeteam/domain/user/user/service/ProfileFacade.java, src/main/java/synk/meeteam/domain/user/user/service/UserServiceImpl.java, src/main/java/synk/meeteam/domain/user/user_link/repository/UserLinkRepository.java, src/main/java/synk/meeteam/domain/user/user_link/service/UserLinkService.java, src/main/java/synk/meeteam/domain/user/user_link/service/UserLinkServiceImpl.java, src/main/java/synk/meeteam/domain/user/user_skill/repository/UserSkillRepository.java, src/main/java/synk/meeteam/domain/user/user_skill/service/UserSkillService.java, src/main/java/synk/meeteam/domain/user/user_skill/service/UserSkillServiceImpl.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java, src/test/java/synk/meeteam/domain/user/user/UserFixture.java, src/test/java/synk/meeteam/domain/user/user_link/UserLinkServiceTest.java, src/test/java/synk/meeteam/domain/user/user_skill/UserSkillServiceTest.java
- feat/#180
- closed #180
- 전체적인 변수명과 함수명을 점검하였습니다.
- 일부 정상 동작안하는 부분을 해결했습니다.
자세한 내용은 이슈에 적어두었습니다!
=> 프로필 조회 및 수정 API 리펙토링 및 버그 해결

src/main/java/synk/meeteam/domain/user/user/service/UserServiceImpl.java
- feat/#213
- closed #213
- 역할 설정할 때, id가 null일 때에 대한 예외처리가 필요하여 추가하였습니다.
=> [FIX] 프로필 수정 API 역할 설정 예외 로직 추가

src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioApi.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioController.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/CreatePortfolioRequestDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/UpdatePortfolioRequestDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/response/GetPortfolioResponseDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio_link/dto/PortfolioLinkDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio_link/entity/PortfolioLink.java
- feat/#208 -> dev
- closed #208
- 등록, 조회, 수정 API에 대한 스웨거 한번에 작업하였습니다.
- **Response**
```json
{
"title": "Meeteam",
"description": "대학생 맞춤형 구인 포트폴리오 서비스",
"content": "밋팀(Meeteam)은 나 자신을 의미하는 Me, 팀을 의미하는 Team, 만남을 의미하는 Meet이 합쳐진 단어입니다.\n대학생들의 보다 원활한 팀프로젝트를 위해 기획하게 되었습니다.\n\n\n밋팀(Meeteam)은 나 자신을 의미하는 Me, 팀을 의미하는 Team, 만남을 의미하는 Meet이 합쳐진 단어입니다.\n대학생들의 보다 원활한 팀프로젝트를 위해 기획하게 되었으며, 그 외에 포토폴리오로서의 기능까지 생각하고 있습니다!\n\n이를 위해 함께 멋진 서비스를 완성할 웹 디자이너를 찾고 있어요!\n밋팀(Meeteam)은 나 자신을 의미하는 Me, 팀을 의미하는 Team, 만남을 의미하는 Meet이 합쳐진 단어입니다.\n대학생들의 보다 원활한 팀프로젝트를 위해 기획하게 되었으며, 그 외에 포토폴리오로서의 기능까지 생각하고 있습니다!\n",
"zipFileUrl": "https://file.zip",
"fileOrder": [
"이미지1.png",
"이미지2.jpg"
],
"field": "개발",
"role": "프론트엔드 개발자",
"startDate": "2023-11-02",
"endDate": "2024-03-15",
"proceedType": "온라인",
"skills": [
{
"id": 1, …
```
=> [DOCS] 포트폴리오 등록,조회,수정 API 스웨거

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/DeleteStatus.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitmentApplicant.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantExceptionType.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_role/entity/RecruitmentRole.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_role/exception/RecruitmentRoleExceptionType.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleServiceTest.java
- feat/
- closed #201 
- 구인 신청 취소 API 구현
- soft delete로 구현하니까 전체적으로 수정되는 로직이 많네요..
- 같은 구인글에 대해서 중복신청 검증 책임이 원래는 레포지토리단에 있었는데 서비스 로직으로 변경했습니다! 그래서 원래 레포지토리에 있던 테스트 코드를 서비스쪽으로 옮겼습니다!
- 함수명도 전체적으로 `add`인 부분이 있어서 `increment` 로 수정했습니다!
- 테스트 코드는 아직 작성하지 못했습니다..! 작성하고 다시 말씀드릴게요..!!
=> [FEAT] 구인 신청 취소 API

src/main/java/synk/meeteam/domain/portfolio/portfolio/exception/PortfolioExceptionType.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioService.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java, src/main/java/synk/meeteam/global/api/ServerProfileController.java, src/main/java/synk/meeteam/global/dto/PreSignedUrlRequestDto.java, src/main/java/synk/meeteam/global/entity/ServiceType.java, src/main/java/synk/meeteam/infra/s3/service/S3Service.java, src/main/java/synk/meeteam/infra/s3/service/vo/PreSignedUrlVO.java, src/test/java/synk/meeteam/domain/user/user/UserFixture.java
- feat/
- closed #216 
- presignedUrl 수정했습니다.
=> [FEAT] PreSignedUrl 서비스 로직에 맞게 구현

src/main/java/synk/meeteam/domain/common/course/repository/CourseRepository.java, src/main/java/synk/meeteam/domain/common/course/repository/ProfessorRepository.java, src/main/java/synk/meeteam/domain/common/course/service/CourseService.java, src/main/java/synk/meeteam/domain/common/course/service/ProfessorService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
=> [FIX] 수업, 교수 저장 방식 수정

.github/workflows/build.yml, .github/workflows/deploy.yml, .gitignore, build.gradle, src/main/java/synk/meeteam/global/common/exception/GlobalExceptionHandler.java, src/main/java/synk/meeteam/infra/discord/DiscordAppender.java, src/main/java/synk/meeteam/infra/discord/DiscordWebHook.java, src/main/java/synk/meeteam/infra/discord/entity/Author.java, src/main/java/synk/meeteam/infra/discord/entity/EmbedObject.java, src/main/java/synk/meeteam/infra/discord/entity/Field.java, src/main/java/synk/meeteam/infra/discord/entity/Footer.java, src/main/java/synk/meeteam/infra/discord/entity/Image.java, src/main/java/synk/meeteam/infra/discord/entity/JsonObject.java, src/main/java/synk/meeteam/infra/discord/entity/Thumbnail.java, src/main/java/synk/meeteam/infra/discord/exception/ErrorLogAppenderException.java, src/main/java/synk/meeteam/infra/discord/exception/ErrorLogAppenderExceptionType.java, src/main/java/synk/meeteam/infra/discord/filter/CachedBodyRequestWrapper.java, src/main/java/synk/meeteam/infra/discord/filter/CachedBodyServletInputStream.java, src/main/java/synk/meeteam/infra/discord/filter/FilterConfig.java, src/main/java/synk/meeteam/infra/discord/filter/MDCFilter.java, src/main/java/synk/meeteam/infra/discord/filter/ServletWrappingFilter.java, src/main/java/synk/meeteam/infra/discord/util/ApiCallUtil.java, src/main/java/synk/meeteam/infra/discord/util/HttpRequestUtil.java, src/main/java/synk/meeteam/infra/discord/util/MDCUtil.java, src/main/java/synk/meeteam/infra/discord/util/StringUtil.java, src/main/resources/console-appender.xml, src/main/resources/discord-appender.xml, src/main/resources/logback-spring.xml
- feat/
- closed 
- 일단 로깅봇 먼저 붙여놨고, 정말 중요한 500에러만 빠르게 로깅하기 위해서 사용될 것 같습니다!
- 이외의 로그는 콘솔쪽보단 로그 파일로 따로 관리할 수 있도록 구현해볼 예정입니다!
=> [FEAT] 디스코드 로깅봇 구현

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java
- feat/
- closed #227 
- 작성자 여부 확인하는 코드가 잘못돼서 수정했습니다
=> [FIX] 작성자 여부 확인 코드 수정

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
- feat/#232 -> dev
- closed #232
- 범위 제한 변경 했습니다.
- 기존 41개 제외 잘 동작합니다.
=> [FIX] Ordinal 범위 제한 수정

src/main/java/synk/meeteam/domain/user/user/entity/User.java
=> [ADD] 처음 접속 여부 추가

src/main/java/synk/meeteam/domain/common/course/service/CourseService.java, src/main/java/synk/meeteam/domain/common/course/service/ProfessorService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
- feat/
- closed #236 
- 구인글 생성 로직 수정
=> [FIX] 구인글 생성 로직 수정

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/SimpleRecruitmentPostMapper.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/PaginationSearchPostResponseDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/SimpleRecruitmentPostDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/main/java/synk/meeteam/global/dto/PageNationDto.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostFixture.java
- feat/#220
- closed #220
- 구인글 관리 api 스웨거입니다.
```json
{
"data": [
{
"id": 1,
"title": "같이할사람 구합니다.",
"category": "프로젝트",
"writerNickname": "goder",
"writerProfileImg": "https://img.png",
"deadline": "2021-12-15",
"scope": "교외",
"isBookmarked": true
}
],
"pageInfo": {
"page": 1,
"size": 24,
"totalContents": 1,
"totalPages": 1
}
}
```
- 현재 userId와 마감여부 필드 제외되어있으나, 구현 시에 추가할 예정입니다. 아래에 필드 명으로 추가될 예정입니다.
- `writerId`
- `isClosed`
- 기존 검색되었을 때 나오는 카드뷰의 정보 또한 위와 같이 변경될 예정입니다.
=> [DOCS] 구인글 관리 API 스웨거

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/DeleteStatus.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitmentApplicant.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostRepository.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/main/java/synk/meeteam/global/entity/DeleteStatus.java
- feat/
- closed #241 
- 구인글 삭제 soft delete로 구현했습니다.
=> [FEAT] 구인글 삭제 API 구현

src/main/java/synk/meeteam/global/aop/ExecutionLoggingAop.java
- feat/
- closed #257
- 포인트컷 수정했습니다
- 스웨거에도 aop 적용돼서 오류가 발생했습니다. 스웨거도 ~~api로 되어있네여
=> [FIX] 포인트컷 수정

src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioApi.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioController.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/SimplePortfolioDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/response/GetPortfolioResponseDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/response/GetUserPortfolioResponseDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/PortfolioMapper.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepository.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementApi.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/main/java/synk/meeteam/domain/user/user/dto/ProfileMapper.java, src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfileResponseDto.java, src/main/java/synk/meeteam/domain/user/user/service/ProfileFacade.java, src/main/java/synk/meeteam/global/dto/PaginationDto.java, src/main/java/synk/meeteam/global/dto/PaginationPortfolioDto.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioFixture.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java, src/test/java/synk/meeteam/domain/user/user/UserFixture.java
- feat/#250 -> dev
- closed #250 -> dev
- 내 포트폴리오 목록 조회 API 스웨거 입니다.
```json
{
"portfolios": [
{
"id": 1,
"title": "Meeteam",
"mainImageUrl": "https://~~",
"field": "개발",
"role": "백엔드 개발자",
"pinOrder": 1,
"pinned": true
}
],
"pageInfo": {
"page": 1,
"size": 10,
"totalContents": 30,
"totalPages": 3
}
}
```
- URL 추천받고 싶습니다.
- 스펙 확인 부탁드립니다.
=> [DOCS] 내 포트폴리오 목록 API 스웨거

src/main/java/synk/meeteam/global/aop/ExecutionLoggingAop.java
- feat/
- closed #261
- Object 리턴하도록 수정
=> [FIX] Object 리턴하도록 수정

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementController.java
- feat/#264 -> dev
- closed #264
- Mapping endpoint 변경하였습니다.
- `myPost`->`my-post`  
- 이전에 논의 하였던 부분이나 제가 실수 하였습니다.
=> [CHORE] endpoint 매핑 변경

.github/workflows/deploy.yml, build.gradle, scripts/deploy.sh, src/main/java/synk/meeteam/domain/auth/api/AuthController.java, src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseDto.java, src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseMapper.java, src/main/java/synk/meeteam/domain/auth/service/vo/AuthUserVo.java, src/main/java/synk/meeteam/domain/common/skill/exception/SkillExceptionType.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java, src/main/java/synk/meeteam/global/api/ServerProfileController.java, src/main/java/synk/meeteam/global/common/exception/GlobalExceptionHandler.java, src/main/java/synk/meeteam/infra/mail/MailService.java, src/main/java/synk/meeteam/infra/mail/MailText.java, src/main/java/synk/meeteam/infra/s3/service/S3Service.java, src/main/java/synk/meeteam/security/jwt/service/JwtService.java
- feat/#247 -> dev
- closed #247
- 최대한 수정사항마다 커밋들을 모아뒀습니다!
- 추가로 액츄에이터를 사용했습니다.
- 기존 헬스체크 API가 취약점이 많다고 판단돼서 진행했는데 다른 의견 있으시면 편하게 말씀주세요!
- 참고자료 : https://techblog.woowahan.com/9232/
- 해당 자료와 같이 Health 체크 부분 외에는 다 막아뒀고, yml도 업데이트 했습니다!
=> [FIX] 여러 수정사항들 반영

appspec.yml
- feat/#268 -> dev
- closed #268
- timeout 시간을 3분으로 변경하였습니다.
=> [INFRA] Code Deploy timeout 시간 변경

docker/Dockerfile
- hotfix/#274 -> dev
- closed #274
- 도커 파일의 tzdata에서 문제가 생긴 것이라 추측되어 변경해보았습니다.
=> [FIX] 시간대 설정을 위한 도커파일 수정

docker/Dockerfile
- hotfix/#278 -> dev
- closed #278
- tzdata 제거
=> [FIX] tzdata 설정 제거

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentManagementRepositoryImpl.java
- feat/#280 -> dev
- closed #280
- 구인글 관리에서 신청한 구인글 조회시에 신청 취소한 구인글이 조회되어 수정하였습니다.
=> [CHORE] 신청 취소한 구인글 제외 처리

docker/Dockerfile
- hotfix/#282 -> dev
- closed #282
- java 명령어에서 시간대 설정을 제거해봤습니다.
=> [FIX] 시간대 설정 옵션 제거

src/main/java/synk/meeteam/global/config/SwaggerConfig.java
- feat/#251 -> dev
- closed #251
- yml에서 도메인을 저희 호스팅된 도메인으로 변경하였습니다.
- 기존에 있던 스웨거의 프론트 도메인 부분을 제거 하였습니다.
=> [CHORE] Server import 추가 및 local 도메인 제거

.github/workflows/build.yml, .github/workflows/deploy.yml
- feat/#287 -> dev
- closed #287
=> [CHORE] 디스코드 알림 봇 수정

src/main/java/synk/meeteam/security/config/SecurityConfig.java
- feat/#290 -> dev
- closed #290
cors 수정
=> [CHORE] cors 수정

.github/workflows/deploy.yml
- feat/#292 -> dev
- closed #292
- 문법오류
=> [FIX] cd 수정

src/main/java/synk/meeteam/global/api/ServerProfileController.java
- feat/#297 -> dev
- closed #297 
- 파일 확장자 제거 로직 추가
=> [FIX] 파일 확장자 제거 로직 추가

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/CreatePortfolioRequestDto.java
=> [ADD] jpeg 추가

src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
- feat/#301 -> dev
- closed #301
=> [CHORE] 구인역할 스킬없는 경우 대응

src/main/java/synk/meeteam/domain/user/award/dto/UpdateAwardDto.java, src/main/java/synk/meeteam/domain/user/user/api/UserApi.java, src/main/java/synk/meeteam/domain/user/user/api/UserController.java, src/main/java/synk/meeteam/domain/user/user/dto/ProfileMapper.java, src/main/java/synk/meeteam/domain/user/user/dto/request/UpdateProfileRequestDto.java, src/main/java/synk/meeteam/domain/user/user/dto/response/GetProfileResponseDto.java, src/main/java/synk/meeteam/domain/user/user/dto/response/ProfileDto.java, src/main/java/synk/meeteam/domain/user/user/entity/User.java, src/main/java/synk/meeteam/domain/user/user/service/ProfileFacade.java, src/main/java/synk/meeteam/domain/user/user/service/UserService.java, src/main/java/synk/meeteam/domain/user/user/service/UserServiceImpl.java, src/test/java/synk/meeteam/domain/user/user/UserControllerTest.java, src/test/java/synk/meeteam/domain/user/user/UserFixture.java
- feat/#252 -> dev
- closed #252
- 유저 프로필 조회 시, 공개여부 고려
- 유저 프로필 수정 시, 입력 정보 유효성 검사 추가
- 프로필 조회 API 변경
자세한 내용은 이슈에 있습니다.
=> [CHORE] 프로필 관련 API 수정

src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioFacade.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java, src/main/java/synk/meeteam/domain/user/user/service/ProfileFacade.java, src/main/java/synk/meeteam/global/api/ServerProfileController.java, src/main/java/synk/meeteam/infra/s3/S3FileName.java
- hotfix/#313 -> dev
- closed #313
- 포트폴리오 업로드 Path 변경
- 포트폴리오 get pre-signedUrl Path 변경
=> [FIX] 포트폴리오 이미지 Path 수정

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java, src/main/java/synk/meeteam/global/config/WebMvcConfig.java, src/main/java/synk/meeteam/global/util/HtmlCharacterEscapes.java, src/main/java/synk/meeteam/global/util/UnescapedFieldSerializer.java, src/test/java/synk/meeteam/global/xss/XssSpringBootTest.java
- feat/#289 -> dev
- closed #289
- XSS 공격 대비를 위한 기능 구현했습니다.
- 기존 설정들이 오염되지 않는 것에 집중했습니다.
- 참고자료 : https://jojoldu.tistory.com/470
- 구인글 내용에만 필터적용을 안하도록 하는게 레퍼런스가 많지 않아 쉽지 않네요.. 
- 커밋된 내용보면 content 필드변수만 RawValue로 저장하도록 해서 이스케이프 처리를 안하도록 구현했습니다.
- 뭔가 레퍼런스를 보고 한게 아니라 디버깅 찍어보면서 구현한거라 사실 좀 불안하기는 합니다. 배포 후에 문제 발생할 경우 롤백해서 다시 수정하도록 하겠습니다.
=> [FEAT] XSS 공격 대비 방어 코드 작성

src/main/java/synk/meeteam/domain/auth/api/AuthController.java, src/main/java/synk/meeteam/domain/auth/dto/response/ReissueUserResponseDto.java, src/main/java/synk/meeteam/domain/auth/service/AuthService.java, src/main/java/synk/meeteam/domain/auth/service/vo/AuthUserVO.java, src/main/java/synk/meeteam/infra/oauth/service/NaverAuthService.java, src/main/java/synk/meeteam/security/filter/JwtAuthenticationFilter.java, src/main/java/synk/meeteam/security/jwt/service/JwtService.java, src/main/java/synk/meeteam/security/jwt/service/JwtTokenProvider.java, src/main/java/synk/meeteam/security/jwt/service/vo/TokenVO.java, src/main/java/synk/meeteam/security/service/MemberAuthService.java
- feat/#311 -> dev
- closed #311 
- 토큰 클레임이 플랫폼 id가 아닌 userId에 의존하도록 개선했습니다.
=> [REFACTOR] 토큰 클레임 플랫폼 종속 개선

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/PostManagementController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/ManageType.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentManagementRepository.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentManagementRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/expression/RecruitmentExpressionUtils.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
- hotfix/#259 -> dev
- closed #259
- 구인글 관리에 북마크 여부가 무조건 True로 오게 되어있어 수정하였습니다.
- 전에 말씀하신 리펙토링 적용했습니다.
=> [FIX] 구인글 관리 북마크 여부 해결 및 관련 코드 리펙토링

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/CreatePortfolioRequestDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/UpdatePortfolioRequestDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioFacade.java, src/main/java/synk/meeteam/domain/portfolio/portfolio_link/dto/PortfolioLinkDto.java, src/main/java/synk/meeteam/domain/user/user/dto/request/UpdateProfileRequestDto.java, src/main/java/synk/meeteam/domain/user/user_link/dto/UpdateUserLinkDto.java, src/main/java/synk/meeteam/security/config/SecurityConfig.java
- feat/#317 -> dev
- closed #317
- 일부 Validation 추가
- 포트폴리오 이미지 오류 수정
- 포트폴리오 조회 로그인 안해도 할 수 있도록 변경
자세한 내용은 이슈에 남겼습니다!
관련 api 포스트맨 추가해놨습니다!
=> [FIX] QA 수정사항 적용

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/response/GetPortfolioResponseDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioFacade.java
- feat/#323 -> dev
- closed #323
- 작성자 닉네임 스펙 추가
=> [ADD] 포트폴리오 작성자 닉네임 스펙 추가

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
- feat/#322 -> dev
- closed #322
- 작성자 검증로직 추가했습니다.
- 수정한 API는 다음과 같습니다.
1. 구인글 수정 API
2. 신청 관리 정보 조회 API
3. 신청자 목록 조회 API
=> [CHORE] 구인글 작성자 검증 로직 추가

src/main/java/synk/meeteam/domain/portfolio/portfolio_link/dto/PortfolioLinkDto.java, src/main/java/synk/meeteam/domain/user/user_link/dto/UpdateUserLinkDto.java
- hotfix/#326 -> dev
- closed #326
- 일부 링크에 대한 검증이 정상적으로 되지 않아 수정하였습니다.
- ex) https://stackoverflow.com/questions/61016202/react-how-to-conditionally-override-textfield-error-color-in-material-ui
=> [FIX] URL regex 수정

src/main/java/synk/meeteam/infra/s3/service/S3Service.java
- feat/#322 -> dev
- closed #322
- 유효시간 변경
=> [CHORE] 유효시간 변경

src/main/java/synk/meeteam/domain/common/role/repository/RoleRepositoryCustomImpl.java, src/main/java/synk/meeteam/domain/common/skill/repository/SkillRepositoryCustomImpl.java, src/main/java/synk/meeteam/domain/common/tag/repository/TagRepositoryCustomImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/expression/RecruitmentExpressionUtils.java
- feat/#334 -> dev
- closed #334
- 각 검색 기능 모두 `contains`로 변경하였습니다.
=> [CHORE] 키워드 검색 방식 변경

src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/expression/RecruitmentExpressionUtils.java
- hotfix/#341 -> dev
- closed #341
- 구인글 조회 시, 다른 학교 구인글이 보이는 이슈를 수정하였습니다.
=> [FIX] 구인글 검색 시, 다른 학교 구인글 보이는 이슈 해결

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/response/GetPortfolioResponseDto.java
- feat/#350 -> dev
- closed #350 
- content에 한하여 이스케이프 적용 해제
=> [CHORE] 이스케이프 적용 해제

src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/facade/RecruitmentApplicantFacade.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/vo/RecruitmentApplicants.java, src/test/java/synk/meeteam/domain/common/skill/SkillRepositoryTest.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java, src/test/java/synk/meeteam/domain/user/user/UserControllerTest.java, src/test/java/synk/meeteam/domain/user/user/UserFixture.java, src/test/java/synk/meeteam/global/xss/XssSpringBootTest.java
- 테스트 코드 All pass 하도록 조금씩 수정했습니다.
- 요즘 좋은 구조가 뭘까에 대해서 많은 고민을 했는데요!
- 테스트 코드 수정하다가 `신청자 승인/거절` 이 부분이 계속 신경쓰였습니다!
- "좋은 설계는 테스트하기가 쉽다"라는 말을 들은 적이 있었는데요. 그리고 그 테스트하기 쉬운 좋은 설계는 DDD 의 개념과 비슷하다는 생각이 많이 들어요. 그래서 List<RecruitmentApplicant> 부분을 일급컬렉션으로 변경해서 서비스레이어가 테스트 하기 쉽게 변경해봤습니다.
- 일급컬렉션 관련 내용 : https://jojoldu.tistory.com/412
- 테스트하기 쉬운 구조 : https://jojoldu.tistory.com/681?category=1036934
- feat/#354 -> dev
- closed #354
=> [REFACTOR] 일급컬렉션 사용 및 테스트 코드 전반 수정

src/main/java/synk/meeteam/security/config/SecurityConfig.java
- feat/#361 -> dev
- closed #361
- 미리보기용 오리진 추가했습니다.
=> [ADD] 미리보기용 오리진 추가

src/main/java/synk/meeteam/global/entity/ProceedType.java
- feat/#363
- closed #363 -> dev
- 진행방식을 온/오프라인으로 변경했습니다.
- DB에도 역할 무관 -> 상관없음 으로 변경했습니다.
=> [CHORE] 상관없음 -> 온/오프라인 변경

.github/workflows/deploy.yml
- hotfix/#366 -> dev
- closed #366
=> [INFRA] 스크립트 경로 수정

src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/command/UpdatePortfolioCommand.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/UpdatePortfolioRequestDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
- hotfix/#387 -> dev
- closed #387
- 기존 포트폴리오 수정 api에 mainImageFileName을 받아오도록 스펙을 추가하였습니다.
- 프론트에서는 이미 요청에 담아 보내도록 했다고 합니다.
=> [FIX] 포트폴리오 메인이미지 변경 오류 해결

README.md
- feat/
- closed 
- ReadMe에 아키텍처랑 ERD 추가했습니다.
=> [DOCS] ReadMe 업데이트

README.md, src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/SimplePortfolioDto.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioCustomRepositoryImpl.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioFacade.java, src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantDto.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/repository/RecruitmentCommentRepositoryCustomImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/vo/RecruitmentCommentVO.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentManagementRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostSearchRepositoryImpl.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/vo/RecruitmentPostVo.java, src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java, src/main/java/synk/meeteam/domain/user/user/api/UserController.java, src/main/java/synk/meeteam/domain/user/user/entity/User.java, src/main/java/synk/meeteam/domain/user/user/service/ProfileFacade.java, src/main/java/synk/meeteam/global/api/ServerProfileController.java, src/main/java/synk/meeteam/infra/aws/service/CloudFrontService.java, src/main/java/synk/meeteam/infra/aws/strategy/NoPortfolioStrategy.java, src/main/java/synk/meeteam/infra/aws/strategy/PortfolioExistStrategy.java, src/main/java/synk/meeteam/infra/aws/strategy/PortfolioStrategy.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioFixture.java, src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java, src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentServiceTest.java, src/test/java/synk/meeteam/domain/user/user/UserFixture.java
- fix/#390 -> main
- Cloudfront url 생성 시, 문자열 버전 쿼리 추가
- 개발서버에서 테스트 완료되어, 운영서버에 적용합니다.
=> [FIX] 이미지 변경 시, 적용 안되는 문제 해결

src/main/java/synk/meeteam/infra/aws/service/CloudFrontService.java
- hotfix/#393 -> main
- closed #393
=> [FIX] 이미지 파일 명 예외 해결
